### ISSUE TITLE
No license and attribution for XML files from Opcodes DB

### ISSUE THREAD

**Issue by Maratyszcza** [mattbierner/Template-Assembly#1]
Nice that you found a use for my Opcodes database, but you should follow the terms of the license.

**Comment by mattbierner** [comment]
I've added an acknowledgement that `x86_64.xml` came from the Opcodes project and linked back to it. Thanks for putting it together by the way, it was by far the easiest x86 documentation to consume for a simple use case like this project.

**Comment by Maratyszcza** [comment]
Thank you!
